/**
 * Mock data for browser preview mode (when Tauri runtime is not available).
 * Provides demo project, floor, walls, APs, and materials for UI preview.
 */

import type {
  ProjectResponse,
  FloorResponse,
  FloorDataResponse,
  WallResponse,
  AccessPointResponse,
  MaterialResponse,
  ApModelResponse,
  AppSettingsResponse,
  HeatmapSettingsResponse,
  MeasurementPointResponse,
} from './invoke';

// ─── IDs ─────────────────────────────────────────────────────────

const DEMO_PROJECT_ID = 'demo-project-001';
const DEMO_FLOOR_ID = 'demo-floor-001';

// ─── Materials (3 Quick-Categories + 13 Detail-Materials) ───────

export const MOCK_MATERIALS: MaterialResponse[] = [
  // ── Quick-Categories (group headers) ──
  {
    id: 'Q01',
    name_de: 'Leichte Wand',
    name_en: 'Light Wall',
    category: 'light',
    default_thickness_cm: 10,
    attenuation_24ghz_db: 4,
    attenuation_5ghz_db: 6,
    attenuation_6ghz_db: 8,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: true,
    icon: null,
  },
  {
    id: 'Q02',
    name_de: 'Mittlere Wand',
    name_en: 'Medium Wall',
    category: 'medium',
    default_thickness_cm: 17.5,
    attenuation_24ghz_db: 12,
    attenuation_5ghz_db: 20,
    attenuation_6ghz_db: 24,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: true,
    icon: null,
  },
  {
    id: 'Q03',
    name_de: 'Schwere Wand',
    name_en: 'Heavy Wall',
    category: 'heavy',
    default_thickness_cm: 20,
    attenuation_24ghz_db: 25,
    attenuation_5ghz_db: 45,
    attenuation_6ghz_db: 52,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: true,
    icon: null,
  },
  // ── Light detail materials ──
  {
    id: 'mat-drywall',
    name_de: 'Gipskarton (einfach)',
    name_en: 'Drywall (single)',
    category: 'light',
    default_thickness_cm: 1.25,
    attenuation_24ghz_db: 2,
    attenuation_5ghz_db: 3,
    attenuation_6ghz_db: 4,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-drywall-double',
    name_de: 'Gipskarton (doppelt)',
    name_en: 'Drywall (double)',
    category: 'light',
    default_thickness_cm: 10,
    attenuation_24ghz_db: 5,
    attenuation_5ghz_db: 7,
    attenuation_6ghz_db: 9,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-wood-stud',
    name_de: 'Holzstaenderwand',
    name_en: 'Wood Stud Wall',
    category: 'light',
    default_thickness_cm: 12,
    attenuation_24ghz_db: 5,
    attenuation_5ghz_db: 8,
    attenuation_6ghz_db: 10,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-wood-door',
    name_de: 'Holztuer (innen)',
    name_en: 'Wood Door (interior)',
    category: 'light',
    default_thickness_cm: 4,
    attenuation_24ghz_db: 4,
    attenuation_5ghz_db: 6,
    attenuation_6ghz_db: 7,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-glass-door',
    name_de: 'Glastuer',
    name_en: 'Glass Door',
    category: 'light',
    default_thickness_cm: 3,
    attenuation_24ghz_db: 3,
    attenuation_5ghz_db: 5,
    attenuation_6ghz_db: 6,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  // ── Medium detail materials ──
  {
    id: 'mat-window',
    name_de: 'Doppelverglasung',
    name_en: 'Double Glazing',
    category: 'medium',
    default_thickness_cm: 2.4,
    attenuation_24ghz_db: 5,
    attenuation_5ghz_db: 9,
    attenuation_6ghz_db: 11,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-brick-thin',
    name_de: 'Ziegelwand (duenn)',
    name_en: 'Brick Wall (thin)',
    category: 'medium',
    default_thickness_cm: 11.5,
    attenuation_24ghz_db: 8,
    attenuation_5ghz_db: 16,
    attenuation_6ghz_db: 19,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-brick',
    name_de: 'Ziegelwand (mittel)',
    name_en: 'Brick Wall (medium)',
    category: 'medium',
    default_thickness_cm: 17.5,
    attenuation_24ghz_db: 10,
    attenuation_5ghz_db: 20,
    attenuation_6ghz_db: 24,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-aac',
    name_de: 'Porenbeton (Ytong)',
    name_en: 'Aerated Concrete (AAC)',
    category: 'medium',
    default_thickness_cm: 17.5,
    attenuation_24ghz_db: 10,
    attenuation_5ghz_db: 18,
    attenuation_6ghz_db: 22,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  // ── Heavy detail materials ──
  {
    id: 'mat-concrete',
    name_de: 'Beton (duenn)',
    name_en: 'Concrete (thin)',
    category: 'heavy',
    default_thickness_cm: 10,
    attenuation_24ghz_db: 15,
    attenuation_5ghz_db: 25,
    attenuation_6ghz_db: 30,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-concrete-medium',
    name_de: 'Beton (mittel)',
    name_en: 'Concrete (medium)',
    category: 'heavy',
    default_thickness_cm: 15,
    attenuation_24ghz_db: 20,
    attenuation_5ghz_db: 35,
    attenuation_6ghz_db: 42,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-reinforced-concrete',
    name_de: 'Stahlbeton',
    name_en: 'Reinforced Concrete',
    category: 'heavy',
    default_thickness_cm: 20,
    attenuation_24ghz_db: 35,
    attenuation_5ghz_db: 55,
    attenuation_6ghz_db: 62,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
  {
    id: 'mat-metal-door',
    name_de: 'Metalltuer',
    name_en: 'Metal Door',
    category: 'heavy',
    default_thickness_cm: 5,
    attenuation_24ghz_db: 18,
    attenuation_5ghz_db: 22,
    attenuation_6ghz_db: 25,
    is_floor: false,
    is_user_defined: false,
    is_quick_category: false,
    icon: null,
  },
];

// ─── AP Models ───────────────────────────────────────────────────

export const MOCK_AP_MODELS: ApModelResponse[] = [
  {
    id: 'model-dap-x2810',
    manufacturer: 'D-Link',
    model: 'DAP-X2810',
    wifi_standard: 'Wi-Fi 6',
    max_tx_power_24ghz_dbm: 20,
    max_tx_power_5ghz_dbm: 23,
    max_tx_power_6ghz_dbm: null,
    antenna_gain_24ghz_dbi: 4,
    antenna_gain_5ghz_dbi: 5,
    antenna_gain_6ghz_dbi: null,
    mimo_streams: 2,
    supported_channels_24ghz: '1,2,3,4,5,6,7,8,9,10,11,12,13',
    supported_channels_5ghz: '36,40,44,48,52,56,60,64,100,104,108,112,116,120,124,128,132,136,140,149,153,157,161,165',
    supported_channels_6ghz: null,
    is_user_defined: false,
  },
];

// ─── Helper ─────────────────────────────────────────────────────

function findMaterial(id: string): MaterialResponse {
  return MOCK_MATERIALS.find((m) => m.id === id) ?? MOCK_MATERIALS[0]!;
}

// ─── Demo Walls ──────────────────────────────────────────────────

const DEMO_WALLS: WallResponse[] = [
  {
    id: 'wall-outer-top',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q03',
    segments: [{ id: 's1', wall_id: 'wall-outer-top', segment_order: 0, x1: 0, y1: 0, x2: 15, y2: 0 }],
    material: findMaterial('Q03'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'wall-outer-right',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q03',
    segments: [{ id: 's2', wall_id: 'wall-outer-right', segment_order: 0, x1: 15, y1: 0, x2: 15, y2: 10 }],
    material: findMaterial('Q03'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'wall-outer-bottom',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q03',
    segments: [{ id: 's3', wall_id: 'wall-outer-bottom', segment_order: 0, x1: 0, y1: 10, x2: 15, y2: 10 }],
    material: findMaterial('Q03'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'wall-outer-left',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q03',
    segments: [{ id: 's4', wall_id: 'wall-outer-left', segment_order: 0, x1: 0, y1: 0, x2: 0, y2: 10 }],
    material: findMaterial('Q03'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'wall-inner-1',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q01',
    segments: [{ id: 's5', wall_id: 'wall-inner-1', segment_order: 0, x1: 7, y1: 0, x2: 7, y2: 6 }],
    material: findMaterial('Q01'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
  {
    id: 'wall-inner-2',
    floor_id: DEMO_FLOOR_ID,
    material_id: 'Q01',
    segments: [{ id: 's6', wall_id: 'wall-inner-2', segment_order: 0, x1: 0, y1: 6, x2: 10, y2: 6 }],
    material: findMaterial('Q01'),
    thickness_cm: null,
    attenuation_override_24ghz: null,
    attenuation_override_5ghz: null,
    attenuation_override_6ghz: null,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
  },
];

// ─── Demo APs ────────────────────────────────────────────────────

const DEMO_APS: AccessPointResponse[] = [
  {
    id: 'ap-living',
    floor_id: DEMO_FLOOR_ID,
    ap_model_id: 'model-dap-x2810',
    label: 'Wohnzimmer',
    x: 3.5,
    y: 3,
    height_m: 2.5,
    mounting: 'ceiling',
    tx_power_24ghz_dbm: 17,
    tx_power_5ghz_dbm: 20,
    tx_power_6ghz_dbm: null,
    channel_24ghz: 1,
    channel_5ghz: 36,
    channel_6ghz: null,
    channel_width: '80',
    band_steering_enabled: false,
    ip_address: null,
    ssid: 'HomeWiFi',
    enabled: true,
    orientation_deg: 0,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
    ap_model: MOCK_AP_MODELS[0]!,
  },
  {
    id: 'ap-office',
    floor_id: DEMO_FLOOR_ID,
    ap_model_id: 'model-dap-x2810',
    label: 'Buero',
    x: 11,
    y: 3,
    height_m: 2.5,
    mounting: 'ceiling',
    tx_power_24ghz_dbm: 17,
    tx_power_5ghz_dbm: 20,
    tx_power_6ghz_dbm: null,
    channel_24ghz: 6,
    channel_5ghz: 48,
    channel_6ghz: null,
    channel_width: '80',
    band_steering_enabled: false,
    ip_address: null,
    ssid: 'HomeWiFi',
    enabled: true,
    orientation_deg: 0,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
    ap_model: MOCK_AP_MODELS[0]!,
  },
  {
    id: 'ap-bedroom',
    floor_id: DEMO_FLOOR_ID,
    ap_model_id: 'model-dap-x2810',
    label: 'Schlafzimmer',
    x: 3.5,
    y: 8,
    height_m: 2.5,
    mounting: 'wall',
    tx_power_24ghz_dbm: 14,
    tx_power_5ghz_dbm: 17,
    tx_power_6ghz_dbm: null,
    channel_24ghz: 11,
    channel_5ghz: 149,
    channel_6ghz: null,
    channel_width: '40',
    band_steering_enabled: false,
    ip_address: null,
    ssid: 'HomeWiFi',
    enabled: true,
    orientation_deg: 0,
    created_at: '2026-01-01',
    updated_at: '2026-01-01',
    ap_model: MOCK_AP_MODELS[0]!,
  },
];

// ─── Assembled Responses ─────────────────────────────────────────

export const MOCK_PROJECT: ProjectResponse = {
  id: DEMO_PROJECT_ID,
  name: 'Demo Wohnung',
  description: 'Beispiel-Projekt mit 3 APs und Innenwaenden',
  floor_plan_width_m: 15,
  floor_plan_height_m: 10,
  locale: 'de',
  created_at: '2026-01-01T10:00:00Z',
  updated_at: '2026-01-01T10:00:00Z',
};

export const MOCK_FLOOR: FloorResponse = {
  id: DEMO_FLOOR_ID,
  project_id: DEMO_PROJECT_ID,
  name: 'Erdgeschoss',
  floor_number: 0,
  background_image_format: null,
  background_image_rotation: 0,
  scale_px_per_meter: 50,
  width_meters: 15,
  height_meters: 10,
  ceiling_height_m: 2.7,
  floor_material_id: null,
  created_at: '2026-01-01T10:00:00Z',
  updated_at: '2026-01-01T10:00:00Z',
};

export const MOCK_FLOOR_DATA: FloorDataResponse = {
  ...MOCK_FLOOR,
  walls: DEMO_WALLS,
  access_points: DEMO_APS,
  measurement_points: [],
};

export const MOCK_SETTINGS: AppSettingsResponse = {
  locale: 'de',
  theme: 'dark',
  default_color_scheme: 'viridis',
  default_grid_resolution_m: 1.0,
  iperf_server_ip: null,
  iperf_server_port: 5201,
  auto_save_enabled: true,
  auto_save_interval_s: 30,
};

export const MOCK_HEATMAP_SETTINGS: HeatmapSettingsResponse = {
  id: 'hs-001',
  project_id: DEMO_PROJECT_ID,
  color_scheme: 'viridis',
  grid_resolution_m: 1.0,
  signal_threshold_excellent: -50,
  signal_threshold_good: -65,
  signal_threshold_fair: -75,
  signal_threshold_poor: -85,
  receiver_gain_dbi: 0,
  path_loss_exponent: 3.0,
  reference_loss_24ghz: 40.05,
  reference_loss_5ghz: 46.68,
  reference_loss_6ghz: 49.2,
  opacity: 0.65,
  show_24ghz: true,
  show_5ghz: true,
  show_6ghz: false,
};
