// =============================================================================
// WLAN-Optimizer TypeScript Type Definitions
// Source: docs/architecture/Datenmodell.md Section 4
// =============================================================================

// -----------------------------------------------------------------------------
// 4.1 Base types
// -----------------------------------------------------------------------------

/** Position in meters relative to floor plan origin (top-left) */
export interface Position {
  x: number;
  y: number;
}

/** Dimensions in meters */
export interface Dimensions {
  width: number;
  height: number;
}

/** Line segment with start and end point */
export interface LineSegment {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export type FrequencyBand = '2.4ghz' | '5ghz' | '6ghz';
export type MaterialCategory = 'light' | 'medium' | 'heavy' | 'blocking';
export type MountingType = 'ceiling' | 'wall' | 'desk';
export type ChannelWidth = '20' | '40' | '80' | '160';
export type WifiStandard = 'wifi5' | 'wifi6' | 'wifi6e' | 'wifi7';
export type ColorScheme = 'viridis' | 'jet' | 'inferno';
export type RunType = 'baseline' | 'post_optimization' | 'verification';
export type MeasurementQuality = 'good' | 'fair' | 'poor' | 'failed';
export type ConfidenceLevel = 'high' | 'medium' | 'low';
export type OptimizationMode = 'forecast' | 'assist' | 'auto';

/** Attenuation values per frequency band */
export interface AttenuationPerBand {
  '2.4ghz': number;
  '5ghz': number;
  '6ghz': number;
}

// -----------------------------------------------------------------------------
// 4.2 Entity interfaces
// -----------------------------------------------------------------------------

export interface Project {
  id: string;
  name: string;
  description: string | null;
  floorPlanWidthM: number | null;
  floorPlanHeightM: number | null;
  locale: 'de' | 'en';
  createdAt: string;
  updatedAt: string;
}

export interface Floor {
  id: string;
  projectId: string;
  name: string;
  floorNumber: number;
  backgroundImage: ArrayBuffer | null;
  backgroundImageFormat: 'png' | 'jpg' | 'pdf' | null;
  scalePxPerMeter: number | null;
  widthMeters: number | null;
  heightMeters: number | null;
  ceilingHeightM: number;
  floorMaterialId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Material {
  id: string;
  nameDe: string;
  nameEn: string;
  category: MaterialCategory;
  defaultThicknessCm: number | null;
  attenuation24ghzDb: number;
  attenuation5ghzDb: number;
  attenuation6ghzDb: number;
  isFloor: boolean;
  isUserDefined: boolean;
  isQuickCategory: boolean;
  icon: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Wall {
  id: string;
  floorId: string;
  materialId: string;
  attenuationOverride24ghz: number | null;
  attenuationOverride5ghz: number | null;
  attenuationOverride6ghz: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface WallSegment {
  id: string;
  wallId: string;
  segmentOrder: number;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

/** Wall with resolved material and segments */
export interface WallWithDetails extends Wall {
  material: Material;
  segments: WallSegment[];
}

export interface ApModel {
  id: string;
  manufacturer: string;
  model: string;
  wifiStandard: WifiStandard | null;
  maxTxPower24ghzDbm: number | null;
  maxTxPower5ghzDbm: number | null;
  maxTxPower6ghzDbm: number | null;
  antennaGain24ghzDbi: number | null;
  antennaGain5ghzDbi: number | null;
  antennaGain6ghzDbi: number | null;
  mimoStreams: number | null;
  supportedChannels24ghz: number[] | null;
  supportedChannels5ghz: number[] | null;
  supportedChannels6ghz: number[] | null;
  isUserDefined: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AccessPoint {
  id: string;
  floorId: string;
  apModelId: string | null;
  label: string | null;
  x: number;
  y: number;
  heightM: number;
  mounting: MountingType;
  txPower24ghzDbm: number | null;
  txPower5ghzDbm: number | null;
  txPower6ghzDbm: number | null;
  channel24ghz: number | null;
  channel5ghz: number | null;
  channel6ghz: number | null;
  channelWidth: ChannelWidth;
  bandSteeringEnabled: boolean;
  ipAddress: string | null;
  ssid: string | null;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Access point with resolved model */
export interface AccessPointWithModel extends AccessPoint {
  apModel: ApModel | null;
}

export interface MeasurementPoint {
  id: string;
  floorId: string;
  label: string;
  x: number;
  y: number;
  autoGenerated: boolean;
  notes: string | null;
  createdAt: string;
}

export interface MeasurementRun {
  id: string;
  floorId: string;
  runNumber: 1 | 2 | 3;
  runType: RunType;
  iperfServerIp: string | null;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

export interface Measurement {
  id: string;
  measurementPointId: string;
  measurementRunId: string;
  timestamp: string;
  frequencyBand: FrequencyBand;
  rssiDbm: number | null;
  noiseDbm: number | null;
  snrDb: number | null;
  connectedBssid: string | null;
  connectedSsid: string | null;
  frequencyMhz: number | null;
  txRateMbps: number | null;
  iperfTcpUploadBps: number | null;
  iperfTcpDownloadBps: number | null;
  iperfTcpRetransmits: number | null;
  iperfUdpThroughputBps: number | null;
  iperfUdpJitterMs: number | null;
  iperfUdpLostPackets: number | null;
  iperfUdpTotalPackets: number | null;
  iperfUdpLostPercent: number | null;
  rttMeanUs: number | null;
  quality: MeasurementQuality;
  rawIperfJson: string | null;
  createdAt: string;
}

export interface CalibrationResult {
  id: string;
  measurementRunId: string;
  frequencyBand: FrequencyBand;
  pathLossExponentOriginal: number;
  pathLossExponentCalibrated: number | null;
  wallCorrectionFactor: number;
  rmseDb: number | null;
  rSquared: number | null;
  maxDeviationDb: number | null;
  numMeasurementPoints: number;
  confidence: ConfidenceLevel;
  createdAt: string;
}

export interface HeatmapSettings {
  id: string;
  projectId: string;
  colorScheme: ColorScheme;
  gridResolutionM: number;
  signalThresholdExcellent: number;
  signalThresholdGood: number;
  signalThresholdFair: number;
  signalThresholdPoor: number;
  receiverGainDbi: number;
  pathLossExponent: number;
  referenceLoss24ghz: number;
  referenceLoss5ghz: number;
  referenceLoss6ghz: number;
  show24ghz: boolean;
  show5ghz: boolean;
  show6ghz: boolean;
  opacity: number;
  createdAt: string;
  updatedAt: string;
}

export interface OptimizationPlan {
  id: string;
  projectId: string;
  name: string | null;
  mode: OptimizationMode;
  status: 'draft' | 'applied' | 'verified';
  predictedRmseImprovementDb: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface OptimizationStep {
  id: string;
  planId: string;
  accessPointId: string;
  stepOrder: number;
  parameter: string;
  oldValue: string | null;
  newValue: string | null;
  descriptionDe: string | null;
  descriptionEn: string | null;
  applied: boolean;
  appliedAt: string | null;
}

// -----------------------------------------------------------------------------
// 4.3 Canvas-specific types
// -----------------------------------------------------------------------------

/** Visual extension for wall on the Konva canvas */
export interface CanvasWall extends WallWithDetails {
  strokeColor: string;
  strokeWidth: number;
  selected: boolean;
  hovered: boolean;
}

/** Visual extension for AP on the Konva canvas */
export interface CanvasAccessPoint extends AccessPointWithModel {
  iconSrc: string;
  selected: boolean;
  dragging: boolean;
  influenceRadiusPx: number | null;
}

/** Visual measurement point on the canvas */
export interface CanvasMeasurementPoint extends MeasurementPoint {
  statusColor: string;
  measuring: boolean;
  completed: boolean;
}

// -----------------------------------------------------------------------------
// 4.4 Heatmap worker types
// -----------------------------------------------------------------------------

/** Request to the heatmap calculation worker */
export interface HeatmapWorkerRequest {
  type: 'calculate';
  payload: {
    dimensions: Dimensions;
    gridResolutionM: number;
    accessPoints: AccessPointForCalculation[];
    walls: WallForCalculation[];
    rfParams: RfModelParams;
    band: FrequencyBand;
    calibration: CalibrationResult | null;
  };
}

/** Response from the heatmap worker */
export type HeatmapWorkerResponse =
  | { type: 'progress'; payload: HeatmapProgress }
  | { type: 'result'; payload: HeatmapResult }
  | { type: 'error'; payload: HeatmapError };

export interface HeatmapProgress {
  progress: number; // 0.0 - 1.0
  phase: 'coarse' | 'fine';
}

export interface HeatmapResult {
  rssiGrid: Float32Array; // RSSI values row-major
  gridWidth: number;
  gridHeight: number;
  calculationTimeMs: number;
}

export interface HeatmapError {
  message: string;
  code: string;
}

/** Reduced AP for the worker (without visual properties) */
export interface AccessPointForCalculation {
  id: string;
  x: number;
  y: number;
  txPowerDbm: number;
  antennaGainDbi: number;
  enabled: boolean;
}

/** Reduced wall for the worker (only geometry + attenuation) */
export interface WallForCalculation {
  segments: LineSegment[];
  attenuationDb: number;
}

/** RF model parameters for calculation */
export interface RfModelParams {
  pathLossExponent: number;
  referenceLossDb: number;
  receiverGainDbi: number;
}

// -----------------------------------------------------------------------------
// 4.5 IPC types (Tauri commands)
// -----------------------------------------------------------------------------

/** Payload for project creation */
export interface CreateProjectPayload {
  name: string;
  description?: string;
  locale?: 'de' | 'en';
}

/** Payload for wall creation */
export interface CreateWallPayload {
  floorId: string;
  materialId: string;
  segments: Omit<WallSegment, 'id' | 'wallId'>[];
}

/** Payload for wall update */
export interface UpdateWallPayload {
  wallId: string;
  materialId?: string;
  segments?: Omit<WallSegment, 'id' | 'wallId'>[];
  attenuationOverride24ghz?: number | null;
  attenuationOverride5ghz?: number | null;
  attenuationOverride6ghz?: number | null;
}

/** Payload for AP creation */
export interface CreateAccessPointPayload {
  floorId: string;
  apModelId?: string;
  label?: string;
  x: number;
  y: number;
  heightM?: number;
  mounting?: MountingType;
}

/** Payload for AP update */
export interface UpdateAccessPointPayload {
  accessPointId: string;
  x?: number;
  y?: number;
  heightM?: number;
  mounting?: MountingType;
  txPower24ghzDbm?: number;
  txPower5ghzDbm?: number;
  channel24ghz?: number;
  channel5ghz?: number;
  channelWidth?: ChannelWidth;
  enabled?: boolean;
}

/** Payload for heatmap settings update */
export interface UpdateHeatmapSettingsPayload {
  projectId: string;
  colorScheme?: ColorScheme;
  gridResolutionM?: number;
  pathLossExponent?: number;
  opacity?: number;
  show24ghz?: boolean;
  show5ghz?: boolean;
}

/** Payload for saving a measurement */
export interface SaveMeasurementPayload {
  measurementPointId: string;
  measurementRunId: string;
  frequencyBand: FrequencyBand;
  rssiDbm?: number;
  noiseDbm?: number;
  iperfTcpUploadBps?: number;
  iperfTcpDownloadBps?: number;
  iperfTcpRetransmits?: number;
  iperfUdpThroughputBps?: number;
  iperfUdpJitterMs?: number;
  iperfUdpLostPackets?: number;
  iperfUdpTotalPackets?: number;
  rawIperfJson?: string;
}

/** Payload for running calibration */
export interface RunCalibrationPayload {
  measurementRunId: string;
  frequencyBand: FrequencyBand;
}
